spring:
    data:
    mongodb:
        port: 27017
        host: localhost
        database: myDatabase
loggin:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG